name    'ghoneycutt-ntp'
version '2.0.4'
source 'git://github.com/ghoneycutt/puppet-module-ntp.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage NTP'
description 'Manages NTP server'
project_page 'https://github.com/ghoneycutt/puppet-module-ntp'

dependency 'puppetlabs/stdlib',  '3.2.x'
dependency 'ghoneycutt/common', '>= 1.0.2'
