name    'ghoneycutt-ntp'
version '3.5.1'
source 'git://github.com/ghoneycutt/puppet-module-ntp.git'
author 'ghoneycutt'
license 'Apache-2.0'
summary 'Manage NTP'
description 'Manages NTP server'
project_page 'https://github.com/ghoneycutt/puppet-module-ntp'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
dependency 'ghoneycutt/common', '>= 1.0.2'
